# Generated by Django 5.2.7 on 2026-02-16 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productoffer',
            old_name='products',
            new_name='product',
        ),
    ]
