# Generated by Django 5.1.5 on 2025-07-16 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0002_user_is_vaerified_user_otp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_vaerified',
            new_name='is_verified',
        ),
    ]
