# Generated by Django 5.1.5 on 2025-07-16 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0003_rename_is_vaerified_user_is_verified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_verified',
        ),
        migrations.AlterField(
            model_name='user',
            name='is_blocked',
            field=models.BooleanField(default=True),
        ),
    ]
