# Generated by Django 5.1.5 on 2025-07-18 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0005_alter_user_is_blocked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_blocked',
            field=models.BooleanField(default=True),
        ),
    ]
