# Generated by Django 5.1.5 on 2025-07-21 04:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Varient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=100)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('main_image', models.ImageField(blank=True, null=True, upload_to='variants/')),
                ('image_1', models.ImageField(blank=True, null=True, upload_to='variants/')),
                ('image_2', models.ImageField(blank=True, null=True, upload_to='variants/')),
                ('image_3', models.ImageField(blank=True, null=True, upload_to='variants/')),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='product.product')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
