# Generated by Django 5.2.11 on 2026-04-02 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='variant',
            unique_together={('product', 'color')},
        ),
        migrations.AlterField(
            model_name='variant',
            name='color',
            field=models.CharField(max_length=64),
        ),
        migrations.DeleteModel(
            name='ProductImage',
        ),
        migrations.RemoveField(
            model_name='variant',
            name='main_image',
        ),
    ]
