# Generated by Django 5.1.5 on 2026-01-19 05:54

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='main_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='product_main_image'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='product_image'),
        ),
        migrations.AlterField(
            model_name='variant',
            name='main_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='variant_main_image'),
        ),
        migrations.AlterField(
            model_name='variantimage',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='variant_image'),
        ),
    ]
