# Generated by Django 5.1.5 on 2025-11-04 12:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category_management', '0001_initial'),
        ('product_management', '0002_auto_20251104_1159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(default=10, on_delete=django.db.models.deletion.PROTECT, related_name='products', to='category_management.category'),
            preserve_default=False,
        ),
    ]
