# Generated by Django 5.2.11 on 2026-05-07 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_management', '0003_product_average_rating_product_review_count'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='variant',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='variant',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('product', 'color'), name='unique_active_variant_color'),
        ),
    ]
