# Generated by Django 5.1.5 on 2025-07-25 04:20

import image_cropping.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_category_description_category_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='cropping',
            field=image_cropping.fields.ImageRatioField('image', '500x500', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='cropping'),
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=image_cropping.fields.ImageCropField(blank=True, null=True, upload_to='categories/'),
        ),
    ]
