# Generated by Django 5.1.5 on 2025-08-09 05:27

import image_cropping.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0003_category_cropping_alter_category_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=image_cropping.fields.ImageCropField(upload_to='categories/'),
        ),
    ]
