# Generated by Django 5.1.5 on 2025-11-26 14:52

import user_profile.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_addresses', '0002_address_is_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(max_length=100, validators=[user_profile.validators.validate_city]),
        ),
        migrations.AlterField(
            model_name='address',
            name='phone',
            field=models.CharField(max_length=20, validators=[user_profile.validators.validate_indian_mobile]),
        ),
        migrations.AlterField(
            model_name='address',
            name='pin_code',
            field=models.CharField(max_length=20, validators=[user_profile.validators.validate_indian_pincode]),
        ),
        migrations.AlterField(
            model_name='address',
            name='state',
            field=models.CharField(max_length=100, validators=[user_profile.validators.validate_state]),
        ),
    ]
