# Generated by Django 5.1.5 on 2025-12-24 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_addresses', '0004_address_is_default'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='email',
        ),
    ]
