# Generated by Django 5.2.11 on 2026-03-24 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_authentication', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otp',
            name='code',
        ),
        migrations.AddField(
            model_name='otp',
            name='code_hash',
            field=models.CharField(default='temp', max_length=64),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='otp',
            name='purpose',
            field=models.CharField(choices=[('signup', 'Signup'), ('reset', 'Password Reset')], max_length=10),
        ),
    ]
