# Generated by Django 5.1.5 on 2025-11-27 14:22

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_authentication', '0002_alter_passwordresetotp_otp_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='otp',
            options={},
        ),
        migrations.RemoveField(
            model_name='otp',
            name='attempts',
        ),
        migrations.RemoveField(
            model_name='otp',
            name='is_used',
        ),
        migrations.RemoveField(
            model_name='passwordresetotp',
            name='is_used',
        ),
        migrations.RemoveField(
            model_name='passwordresetotp',
            name='otp',
        ),
        migrations.AddField(
            model_name='passwordresetotp',
            name='code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='otp',
            name='code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='otp',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='otp',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='passwordresetotp',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='passwordresetotp',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
