# Generated by Django 5.2.11 on 2026-05-07 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category_management', '0003_alter_category_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='image',
        ),
    ]
