# Generated by Django 5.2.11 on 2026-05-05 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_orderitem_coupon_discount_amount_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='order',
            name='orders_orde_status_c6dd84_idx',
        ),
        migrations.RemoveIndex(
            model_name='order',
            name='orders_orde_created_0e92de_idx',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='cancellation_reason',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='coupon_discount_amount',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='return_reason',
        ),
    ]
