# Generated by Django 5.2.11 on 2026-05-06 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_remove_order_orders_orde_status_c6dd84_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='coupon_discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
