# Generated by Django 5.1.5 on 2025-11-26 13:23

import user_profile.models
import user_profile.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='pincode',
            field=models.CharField(blank=True, max_length=6, validators=[user_profile.validators.validate_indian_pincode]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='city',
            field=models.CharField(blank=True, max_length=100, validators=[user_profile.models.validate_city]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='mobile',
            field=models.CharField(blank=True, max_length=20, validators=[user_profile.validators.validate_indian_mobile]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='state',
            field=models.CharField(blank=True, max_length=100, validators=[user_profile.models.validate_state]),
        ),
    ]
