# Generated by Django 5.1.5 on 2025-12-24 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0002_profile_pincode_alter_profile_city_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='city',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='pincode',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='primary_address',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='state',
        ),
    ]
